[build]
  command = "npm run build"
  publish = "build"

# Handles SPA routing (so direct URL access works)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[dev]
  command = "npm start"
  framework = "create-react-app" 